plugins {
    id 'java'
}

group = 'kuke'
version = '1'

allprojects {
    repositories {
        mavenCentral()
    }

    apply plugin: 'java'

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok:1.18.30'
        annotationProcessor 'org.projectlombok:lombok:1.18.30'

        testCompileOnly 'org.projectlombok:lombok:1.18.30'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'

        testImplementation 'org.springframework.boot:spring-boot-starter-test:3.3.2'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}
