plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'Green-Basket'

// 서비스 모듈
include 'user-service'
include 'apigateway-service'
include 'service-discovery'

// 공통 모듈
include 'common:snowflake'
include 'common:jwt'
include 'common:id-generator'
include 'common:exception'
//include 'common:outbox-message-relay'
//include 'common:event'
include 'order-service'
include 'catalog-service'
include 'config-service'
include 'common:data-serializer'
findProject(':common:data-serializer')?.name = 'data-serializer'
include 'common:data-serializer'
findProject(':common:data-serializer')?.name = 'data-serializer'
include 'catalog-interaction-service'
include 'hot-catalog-service'
include 'common:event'
findProject(':common:event')?.name = 'event'
include 'common:outbox-message-relay'
findProject(':common:outbox-message-relay')?.name = 'outbox-message-relay'

