# Server Configuration
server.port=0

# Feign Circuit Breaker
feign.circuitbreaker.enabled=true


# Note: All other configurations are loaded from Config Server
# See: bootstrap.properties for config server connection settings
# Config Repository: https://github.com/pryeok/Green-Basket-Config/blob/main/catalog-read-service.yml
