# Server Configuration
server.port=8888

# Spring Application Configuration
spring.application.name=config-service

# RabbitMQ Configuration
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=greenbasket
spring.rabbitmq.password=greenbasket

# Enable RabbitMQ and Spring Cloud Bus
spring.cloud.bus.enabled=true

# Spring Profiles
spring.profiles.active=git

# Native File Repository (commented out)
#spring.cloud.config.server.native.search-locations=file:///C:/Users/박력/Desktop/Workspace/msa/native-file-repo

# Git Repository Configuration
spring.cloud.config.server.git.uri=https://github.com/pryeok/Green-Basket-Config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.username=pryeok@gmail.com
spring.cloud.config.server.git.password=qkrfur124$

# Eureka Client Configuration
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Management Endpoints
management.endpoints.web.exposure.include=refresh,health,beans,info,busrefresh