plugins {
    id 'java'
    id 'java-library'
}

group = 'com.greenbasket.common'
version = '1.0.0'
sourceCompatibility = '21'
targetCompatibility = '21'

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot
    compileOnly 'org.springframework.boot:spring-boot-starter:3.5.0'
    compileOnly 'org.springframework:spring-context:6.2.0'
    compileOnly 'org.springframework:spring-web:6.2.0'

    // Spring Security (Filter 관련)
    compileOnly 'org.springframework.security:spring-security-core:6.4.1'
    compileOnly 'org.springframework.security:spring-security-web:6.4.1'

    // JWT
    api 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    // Servlet API
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // Jackson (JSON 처리)
    compileOnly 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
}
