server.port=8000
spring.application.name=apigateway-service

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

# RabbitMQ Configuration
#spring.rabbitmq.host=127.0.0.1
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
spring.cloud.bus.enabled=false
spring.rabbitmq.listener.simple.auto-startup=false

# Spring Cloud Gateway Global Filter
#spring.cloud.gateway.server.webflux.default-filters[0].name=GlobalFilter
#spring.cloud.gateway.server.webflux.default-filters[0].args.baseMessage=Spring Cloud Gateway WebFlux Global Filter
#spring.cloud.gateway.server.webflux.default-filters[0].args.preLogger=true
#spring.cloud.gateway.server.webflux.default-filters[0].args.postLogger=true

# Route 0: User Service - Public API (?? ???: ????, ???, ?????)
spring.cloud.gateway.routes[0].id=user-service-public
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/user-service/users,/user-service/auth/**,/user-service/redis-test/**
spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[0].filters[1]=RewritePath=/user-service/(?<segment>.*), /$\{segment}

# Route 1: User Service - Protected API (?? ??)
spring.cloud.gateway.routes[1].id=user-service-protected
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/user-service/**
spring.cloud.gateway.routes[1].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[1].filters[1]=RewritePath=/user-service/(?<segment>.*), /$\{segment}
spring.cloud.gateway.routes[1].filters[2]=JwtAuthentication

# Route 4: Catalog Service
#spring.cloud.gateway.routes[3].id=catalog-service
#spring.cloud.gateway.routes[3].uri=lb://CATALOG-SERVICE
#spring.cloud.gateway.routes[3].predicates[0]=Path=/catalog-service/**

# Route 5: Order Service
#spring.cloud.gateway.routes[4].id=order-service
#spring.cloud.gateway.routes[4].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.routes[4].predicates[0]=Path=/order-service/**

# JWT Token
token.access-expiration-time=1800000
token.refresh-expiration-time=604800000
token.secret=my-very-long-secret-key-1234567890123456-greenbasket-2024

# Management Endpoints (busrefresh ?? - RabbitMQ ???)
management.endpoints.web.exposure.include=refresh,health,beans,info,httpexchanges
management.health.rabbit.enabled=false
